services:
  app:
    container_name: obsidian-enhanced
    build: .
    volumes:
      - ./app:/app
      - ./vault:/vault
      - ./logs:/app/logs
      - ./tests:/tests
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO

